Programa 1

In [4]:
import threading
from threading import Thread, Lock, RLock
import random
import time
import sys

class Tortuga(Thread):
  def __init__(self,inicio,fin,meta,lock):
    super(Tortuga,self).__init__()
    self.fin=fin
    self.inicio=inicio
    self.posicion=1
    self.meta=meta
    self.lock=lock
    self.timeStamp=float('inf')
  
  def run(self):
    while self.posicion<self.fin:
      time.sleep(1)
      self.suceso(random.random())
      sys.stdout.write(f"posicion-{self.posicion} T\n")

    self.timeStamp=time.time()

  def suceso(self,probabilidad):
    if 0<probabilidad<=0.5:
      self.posicion+=3

    elif 0.5<probabilidad<=0.7:
      self.posicion-=6

    elif 0.7<probabilidad<=1.0:
      self.posicion+=1
    
    if self.posicion<1:
      self.posicion=1


class Liebre(Thread):
  def __init__(self,inicio,fin,meta,lock):
    super(Liebre,self).__init__()
    self.fin=fin
    self.inicio=inicio
    self.posicion=1
    self.meta=meta
    self.lock=lock
    self.timeStamp=float('inf')
  
  def run(self):
    while self.posicion<self.fin:
      time.sleep(1)
      self.suceso(random.random())
      sys.stdout.write(f"posicion-{self.posicion} L\n")
      
    self.timeStamp=time.time()

  def suceso(self,probabilidad):
    if 0.2<probabilidad<=0.4:
      self.posicion+=9

    elif 0.4<probabilidad<=0.5:
      self.posicion-=12

    elif 0.5<probabilidad<=0.8:
      self.posicion+=1

    elif 0.8<probabilidad<=1.0:
      self.posicion-=2

    if self.posicion<1:
      self.posicion=1  


if __name__=="__main__":
  meta=[]
  lock=Lock()
  inicio=1
  fin=70
  T=Tortuga(inicio,fin,meta,lock)
  L=Liebre(inicio,fin,meta,lock)

  T.start()
  L.start()

  T.join()
  L.join()

  if L.timeStamp==T.timeStamp:
    sys.stdout.write("Empate")
  elif L.timeStamp<T.timeStamp:
    sys.stdout.write("Gano la Liebre")  
  elif T.timeStamp<L.timeStamp:
    sys.stdout.write("Gano la Tortuga")

posicion-2 T
posicion-1 L
posicion-5 T
posicion-2 L
posicion-8 T
posicion-11 L
posicion-12 L
posicion-9 T
posicion-13 L
posicion-12 T
posicion-14 L
posicion-15 T
posicion-14 L
posicion-16 T
posicion-12 L
posicion-17 T
posicion-21 L
posicion-18 T
posicion-19 L
posicion-21 T
posicion-22 T
posicion-20 L
posicion-21 L
posicion-23 T
posicion-26 T
posicion-19 L
posicion-19 L
posicion-20 T
posicion-17 L
posicion-14 T
posicion-17 T
posicion-5 L
posicion-11 T
posicion-5 L
posicion-12 T
posicion-14 L
posicion-6 T
posicion-12 L
posicion-7 T
posicion-10 L
posicion-1 T
posicion-19 L
posicion-1 T
posicion-28 L
posicion-4 T
posicion-26 L
posicion-27 L
posicion-7 T
posicion-25 L
posicion-8 T
posicion-9 T
posicion-25 L
posicion-3 T
posicion-23 L
posicion-6 T
posicion-32 L
posicion-1 T
posicion-30 L
posicion-2 T
posicion-31 L
posicion-3 T
posicion-32 L
posicion-4 T
posicion-41 L
posicion-5 T
posicion-39 L
posicion-1 T
posicion-40 L
posicion-4 T
posicion-38 L
posicion-38 L
posicion-1 T
posicion-39 L
posi

Programa 2

Producto de dos matrices secuencial

In [16]:
import numpy as np
import time
import queue
from queue import Queue

m1 = np.random.randint(0, 100, (100, 100))
m2 = np.random.randint(0, 100, (100, 100))

print("\nM1:\n",m1)
print("\nM2:\n",m2)

def producto(m1,m2):
  if m1.shape[1]==m2.shape[0]:
    resultado=np.zeros((m1.shape[0],m1.shape[0]))
    for i in range(m1.shape[0]):
      for j in range(m2.shape[1]):
        for k in range(m1.shape[1]):
          resultado[i][j] = m1[i][k]*m2[k][j]
    return resultado
  else:
    print('Las matrices no son compatibles')
    return

t=time.time()
mult=producto(m1,m2)
print("\nMultiplicacion secuencial:")
print("M1*M2:\n",mult)
print('\nTiempo total:',time.time()-t)


M1:
 [[28  2 30 ... 85 24 18]
 [92 96 36 ... 55  7 79]
 [26 69 97 ... 99 35 13]
 ...
 [76 16  9 ... 78 89 93]
 [34 61 13 ... 19 64 68]
 [79 98 49 ...  9 39 83]]

M2:
 [[ 0 32 98 ... 39 95  3]
 [77 31 90 ... 52 20 31]
 [98 17 21 ... 41 27 82]
 ...
 [29 16 47 ... 86 23 48]
 [ 9 60 83 ... 15 76 23]
 [57 39 13 ... 21 47 19]]

Multiplicacion secuencial:
M1*M2:
 [[1026.  702.  234. ...  378.  846.  342.]
 [4503. 3081. 1027. ... 1659. 3713. 1501.]
 [ 741.  507.  169. ...  273.  611.  247.]
 ...
 [5301. 3627. 1209. ... 1953. 4371. 1767.]
 [3876. 2652.  884. ... 1428. 3196. 1292.]
 [4731. 3237. 1079. ... 1743. 3901. 1577.]]

Tiempo total: 1.0304665565490723


In [17]:
import numpy as np
import time
import queue
from queue import Queue

m1 = np.random.randint(0, 100, (100, 100))
m2 = np.random.randint(0, 100, (100, 100))

print("\nM1:\n",m1)
print("\nM2:\n",m2)

def multiplicacionMatriz(mutex,cola,m1,m2,resultado):
    while not(cola.empty()):
        mutex.acquire()
        i=cola.get()
        mutex.release()
        for j in range(100):
          for k in range(100):
            resultado[i,j]+=m1[i,k] * m2[k,j]

if __name__=="__main__":
    mutex=RLock()
    cola=Queue()
    contador=0
    resultado=np.zeros((m1.shape[0],m1.shape[0]))

    for i in range(100):
        cola.put(i)

    t=time.time()
    hilo1=Thread(target=multiplicacionMatriz, args=(mutex,cola,m1,m2,resultado))
    hilo2=Thread(target=multiplicacionMatriz, args=(mutex,cola,m1,m2,resultado))
    hilo3=Thread(target=multiplicacionMatriz, args=(mutex,cola,m1,m2,resultado))
    hilo4=Thread(target=multiplicacionMatriz, args=(mutex,cola,m1,m2,resultado))
    
    hilo1.start()
    hilo2.start()
    hilo3.start()
    hilo4.start()
    
    hilo1.join()
    hilo2.join()
    hilo3.join()
    hilo4.join()

    print("\nMultiplicacion Concurrente:")
    print("M1*M2:\n",resultado)
    print('\nTiempo total:',time.time()-t)


M1:
 [[ 2 85 95 ... 98 15 72]
 [91 81 75 ... 57  7 85]
 [18 58 85 ...  1 54 86]
 ...
 [16 70 43 ... 32 85 21]
 [49 60 51 ... 86 96 10]
 [80 38 70 ... 89 80 10]]

M2:
 [[31 27 43 ... 71 62  8]
 [93  5 70 ...  4 50 53]
 [ 6 46 45 ...  8 29 18]
 ...
 [34 60 52 ... 27  1 81]
 [29 88 99 ... 46 14 37]
 [92 38  5 ... 81 29 87]]

Multiplicacion Concurrente:
M1*M2:
 [[279721. 239449. 248376. ... 251191. 236397. 269152.]
 [259630. 228073. 253257. ... 264321. 255808. 263782.]
 [265070. 218706. 259060. ... 259703. 248005. 247961.]
 ...
 [283863. 237364. 277503. ... 260825. 251377. 270045.]
 [258893. 213843. 253913. ... 259869. 227849. 247972.]
 [241884. 211244. 242358. ... 248877. 224370. 234660.]]

Tiempo total: 0.8970041275024414


Produto de Matrices con 4 hilos: